server:
  shutdown_timeout: 30s
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 10s

mongo:
  database : "image_uploader_test"
  compressors: ["zlib","snappy"]
  max_pool_size: 10
  read_preference: "nearest"
  nodes:
    - host: "127.0.0.1"
      port: 27017